### ISSUE TITLE
Error: Unable to save resume file: File name too long

### ISSUE THREAD

**Issue by one-quaker** [transmission/transmission#122]
If I try add magnet link via transmission-daemon web-interface - I got error "Error: Unable to save resume file: File name too long".
If I add torrent file, all ok.
Deluge torrent client works fine with same magnet link.
I think problem in long name of temporary torrent file, who made from magnet link.

OS: Linux (raspbian arm32), Transmission-2.92 (2.84 have same problem), FS: Ext4

[censored]

Magnet link for test: [censored]

**Comment by one-quaker** [comment]
How you can reproduce bug if magnet link deleted?

**Comment by mikedld** [comment]
That's a good question. Suppose the link should've pointed to legal content in the first place...

**Comment by cfpp2p** [comment]
magnet:?xt=urn:btih:0403fb4728bd788fbcb67e87d6feb241ef38c75a&dn=ubuntu-16.10-desktop-amd64.iso-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long-this-name-is-too-long&tr=http%3A%2F%2Ftorrent.ubuntu.com%3A6969%2Fannounce&tr=http%3A%2F%2Fipv6.torrent.ubuntu.com%3A6969%2Fannounce

**Comment by one-quaker** [comment]
This magnet link have same problem. Thank you **cfpp2p**

**Comment by Hukuta** [comment]
"Error: Unable to save resume file: File name too long" is a popular problem for me. 
I can't download some files with transmission, but with utorrent I can download same files to the same location (via virtual machine with windows and shared folder). 

Will be fixed?

**Comment by rivera15071976** [comment]
Please use long path tool

**Comment by Hukuta** [comment]
What tool? How to use? 
uTorrent saves this file in windows without any problems, why transmission can't?

**Comment by one-quaker** [comment]
And deluge saves without any problems. Why transmission? - it's a good question

**Comment by cfpp2p** [comment]
As in my example above (https://github.com/transmission/transmission/issues/122#issuecomment-270463467) you could just text edit manually the name portion of any magnet (begins with **&dn=**) down to a short(er) length. Or you can patch metainfo.c at  **_maybe get the display name_**. It's only a temporary display name until the real metadata is acquired.

```
          /* maybe get the display name */
          if (tr_variantDictFindStr (d, TR_KEY_display_name, &str, &len))
            {
              tr_free (inf->name);
              tr_free (inf->originalName);
              if (len > 50)
                {
                  inf->name = tr_strndup (str, 50);
                  inf->originalName = tr_strndup (str, 50);
                }
              else
                {
                 inf->name = tr_strndup (str, len);
                 inf->originalName = tr_strndup (str, len);
                }
            }
```
ref: https://github.com/cfpp2p/transmission/commit/bf1d8bb20f41ec0963c128b4368b820d39d19702#diff-d54a64807eeb84d2c1ffec36a2dd76c1

**Comment by v6** [comment]
// , I can confirm I have this, too. 

![image](https://cloud.githubusercontent.com/assets/5750764/23577322/e951f8b8-0070-11e7-89f9-e95e5e05d87c.png)

**Comment by pik** [comment]
Same issue, I don't seem to be able to rename the file on opening a magnet-link (properly this error should prompt for a rename or something of the like?)

**Comment by v6** [comment]
// , Has anyone tested the work around that @cfpp2p proposed?

**Comment by cfpp2p** [comment]
@v6 It is and has been working perfectly for me without issue.

**Comment by pabloab** [comment]
I'm wrong or [this bug was here from 2011](https://bugs.launchpad.net/ubuntu/+source/transmission/+bug/788626). I'm having this problem with [this magnet link](magnet:?xt=urn:btih:2879f3b588ea65a868a95d070c9e95bbec1139fc&dn=Windows%20XP%20PRO%20Profesional%20con%20Service%20Pack%203%20SP3%20Integrado%20con%20serial%20y%20utilidad%20para%20crear%20disquetes%20de%20inicio%20%28Spanish%20-%20SP%20-%20ES%20-%20Espa%C3%B1ol%29.iso&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969) 480 B long.

**Comment by pik** [comment]
I believe this might happen due to use of non-standar encodings such as KOI8R in the torrent name.

**Comment by apolukhin** [comment]
This issue happens annoyingly often. Are there any plans to fix it?

**Comment by v6** [comment]
// , Seems like it could potentially be easy enough for someone to fix if
they're familiar with the system.

**Comment by kov-serg** [comment]
WTF. I have the same proble today on my Ubuntu 14.04.
I have to find out reason. So get source 
mkdir tr && cd tr
apt-get source transmission-gtk
And find error grep 'Unable to save resume file' -R .
Error message is in transmission-2.82/libtransmission/resume.c
```
  filename = getResumeFilename (tor);
  if ((err = tr_variantToFile (&top, TR_VARIANT_FMT_BENC, filename)))
    tr_torrentSetLocalError (tor, "Unable to save resume file: %s", tr_strerror (err));
```
It calls getResumeFilename from the same file
```
static char*
getResumeFilename (const tr_torrent * tor)
{
  char * base = tr_metainfoGetBasename (tr_torrentInfo (tor));
  char * filename = tr_strdup_printf ("%s" TR_PATH_DELIMITER_STR "%s.resume",
                                      tr_getResumeDir (tor->session), base);
  tr_free (base);
  return filename;
}
```
So the solution is to modify tr_metainfoGetBasename

let modify file transmission-2.82/libtransmission/metainfo.c
from
```
char*
tr_metainfoGetBasename (const tr_info * inf)
{
  size_t i;
  const char * name = inf->originalName;
  const size_t name_len = strlen (name);
  char * ret = tr_strdup_printf ("%s.%16.16s", name, inf->hashString);

  for (i=0; i<name_len; ++i)
    if (ret[i] == '/')
      ret[i] = '_';

  return ret;
}
```
to
```
char*
tr_metainfoGetBasename (const tr_info * inf)
{
  size_t i;
  enum { name_max=32 }; char name[name_max+1];
  const char * full_name;
  size_t name_len;
  char *ret;
  
  full_name = inf->originalName;
  name_len = 0;

  for(i=0;;i++) {
  	char c=full_name[i]; if (!c) break;
  	if ((c&0xC0)==0xC0 || ((c&0x80)==0)) { if (i>=name_max) break; name_len=i; }
  }
  strncpy(name,full_name,name_len);

  ret = tr_strdup_printf ("%s.%16.16s", name, inf->hashString);

  for (i=0; i<name_len; ++i)
    if (ret[i] == '/')
      ret[i] = '_';

  return ret;
}
```
I assume utf8 encoding. This limit internal names to 32+17 chars or about. Limit is defined in name_max constant.
then ./configure && make
You can test it running from transmission-2.82/gtk/transmission-gtk
But you have to remove ~/.config/transmission directory or convert names into new scheeme.
Now it downloads any file without problems.

**Comment by pabloab** [comment]
Hi @kov-serg,
v2.82 of Ubuntu 14.04 is pretty old. Seems you are talking about [this lines](https://github.com/transmission/transmission/blob/master/libtransmission/metainfo.c#L39) on master branch. Could you please made a pull request against current source code? Or at least attach a patch file to this issue. Probably this could improve chances of having tested and added to the main source branch.
Thanks!

**Comment by kov-serg** [comment]
Ununtu 14.04 is work well and I see no reasons to change it on something else.
Here is git diff
```
diff --git a/libtransmission/metainfo.c b/libtransmission/metainfo.c
index 51b0659..1fbf63d 100644
--- a/libtransmission/metainfo.c
+++ b/libtransmission/metainfo.c
@@ -38,11 +38,24 @@ static inline bool char_is_path_separator(char c)
 
 char* tr_metainfoGetBasename(tr_info const* inf)
 {
-    char const* name = inf->originalName;
-    size_t const name_len = strlen(name);
-    char* ret = tr_strdup_printf("%s.%16.16s", name, inf->hashString);
+    size_t i;
+    enum { name_max=32 }; char name[name_max+1];
+    const char * full_name;
+    size_t name_len;
+    char *ret;
+
+    full_name = inf->originalName;
+    name_len = 0;
+
+    for(i=0;;i++) {
+        char c=full_name[i]; if (!c) break;
+        if ((c&0xC0)==0xC0 || ((c&0x80)==0)) { if (i>=name_max) break; name_len=i; }
+    }
+    strncpy(name,full_name,name_len);
+
+    ret = tr_strdup_printf ("%s.%16.16s", name, inf->hashString);
 
-    for (size_t i = 0; i < name_len; ++i)
+    for (i = 0; i < name_len; ++i)
     {
         if (char_is_path_separator(ret[i]))
         {
```

**Comment by kov-serg** [comment]
here is script to convert old ~/.config/transmission files
conv.lua
```
#!/usr/bin/lua

function short_name(fn)
	local function short(s,n)
		local i,j,c
		j=1 i=1 while i<=#s do c=s:byte(i)
			if c<128 or c>=192 then if i>=n then break end j=i end
			i=i+1
		end
		if i>#s then j=i end
		return s:sub(1,j-1)
	end
	local path,name,hash_ext = fn:match "^(.*/)([^/]*)(%.%x+%.%w+)$"
	if not path then return nil end
	name=short(name,32)
	return path..name..hash_ext
end

function safe(s) return s:gsub('[`"]','\\%1') end

while true do
	local name=io.read() if not name then break end
	short=short_name(name)
	if short and name~=short then print('mv "'..safe(name)..'" "'..safe(short)..'"') end
end
```
```
cd ~/.config/transmission && find | lua conv.lua > rename-script.sh
```
and then bash rename-script.sh

**Comment by cfpp2p** [comment]
We don't need to filter the torrent name for Cyrillic characters or such. The name length should only be limited to 255.  This way we won't need to convert .config files. Tested with @kov-serg Zelezko2009.torrent (and others).


``` c

#define MAX_NAME_LENGTH 219
// 219 + 36 = 255
// . + 16_byte_hash + .torrent + .tmp.XXXXXX = 36 bytes
// . + 16_byte_hash + .resume + .tmp.XXXXXX = 35 bytes
// see tr_variantToFile() for more explanation

char* tr_metainfoGetBasename(tr_info const* inf)
{
    char const* name = inf->originalName;
    char* shortName;

    if (!strlen(name))
    {
        // allow empty name -- substitute
        shortName = tr_strdup("Hash-Name-");
    }
    else if (strlen(name) <= MAX_NAME_LENGTH)
    {
        shortName = tr_strdup(name);
    }
    else
    {
        // truncate
        shortName = tr_strndup(name, MAX_NAME_LENGTH);
    }

    char* ret = tr_strdup_printf("%s.%16.16s", shortName, inf->hashString);
    size_t const name_len = strlen(shortName);
    tr_free(shortName);

    for (size_t i = 0; i < name_len; ++i)
    {
        if (char_is_path_separator(ret[i]))
        {
            ret[i] = '_';
        }
    }

    return ret;
}
```

**Comment by kov-serg** [comment]
Yes you need or it could split unicode symbol that presented with several bytes. Not noly cyrilic (кирилица) but also japanise (日本語の文字) characters could be in names. So you have to split symbols correctly.

I see not reason to have such long (219 bytes) names. There is a hash and name could be removed at all. But it could help if you try to find something by hands. You may create special function to shorten names and convert to something meaningfull but short. Moreover you have create some thing to migrate for old version to new and backward.

**Comment by cfpp2p** [comment]
Truncating like this may not display as pretty as it could, but there will only be a single split symbol just before the hash string for the both the .resume file and transmission's internal .torrent copy. Transmission will process these torrents without issue. We don't need to convert because the only torrents truncated are those that wouldn't have saved .torrent or .resume previously because of the filename to long issue.

**Comment by kov-serg** [comment]
Why you don't want to split correctly. It will work with transmission but may cause problems in other applications.

**Comment by cfpp2p** [comment]
@kov-serg  OK with you?,` tr_utf8clean()`. Set the `MAX_NAME_LENGTH` as you wish. Please test for your liking.

``` c
#define MAX_NAME_LENGTH 219
// 219 + 36 = 255
// . + 16_byte_hash + .torrent + .tmp.XXXXXX = 36 bytes
// . + 16_byte_hash + .resume + .tmp.XXXXXX = 35 bytes
// see tr_variantToFile() for more explanation

char* tr_metainfoGetBasename(tr_info const* inf)
{
    char const* name = inf->originalName;
    char* shortName;
    char* cleanName;

    if (!strlen(name))
    {
        // allow empty name -- substitute
        cleanName = tr_strdup("Hash-Name-");
    }
    else if (strlen(name) <= MAX_NAME_LENGTH)
    {
        cleanName = tr_strdup(name);
    }
    else
    {
        // truncate
        shortName = tr_strndup(name, MAX_NAME_LENGTH);
        cleanName = tr_utf8clean(shortName, -1);
    }
    tr_free(shortName);

    char* ret = tr_strdup_printf("%s.%16.16s", cleanName, inf->hashString);
    size_t const name_len = strlen(cleanName);
    tr_free(cleanName);

    for (size_t i = 0; i < name_len; ++i)
    {
        if (char_is_path_separator(ret[i]))
        {
            ret[i] = '_';
        }
    }

    return ret;
}
```

**Comment by Proga** [comment]
May I suggest couple improvements to the code?
char* shortName=NULL;
char* cleanName=NULL;

And move tr_free(shortName);  into the else scope, vise versa an unallocated memory is got free and a result - segfault. 
else
    {
        // truncate
        shortName = tr_strndup(name, MAX_NAME_LENGTH);
        cleanName = tr_utf8clean(shortName, -1);
        tr_free(shortName); // free allocated memory
    }

**Comment by cfpp2p** [comment]
@Proga The 2.9x branch didn't end up using that code. However, completed along those lines please see:
https://github.com/cfpp2p/transmission/blob/svn/trunk/libtransmission/metainfo.c#L43

from commits:
https://github.com/cfpp2p/transmission/commit/5e660aed911c349165ca16d1ea818c8cb4cefe42
https://github.com/cfpp2p/transmission/commit/5b7532feae2fe7db4955e8e2b1b63dec6b5bfb87
https://github.com/cfpp2p/transmission/commit/f04795f16b54af9da030849dfcbe0dd49e2e52e9

I think everything looks OK. Thanks for having a look! Please let me know if you see any problems.

**Comment by Proga** [comment]
The commit looks much better! I think there is no attempt to free un allocated memory.
Probably, I will try to check out this brunch.

I found out that solve the problem with too long file names on 2.92. I have to modify 2 other functions:
metainfo.c:
static char*
getTorrentFilename (const tr_session * session, const tr_info * inf)
{

   const char * resume_dir = tr_getTorrentDir (session);
   size_t max_allowed_length = 255 - 1 - strlen(resume_dir);

   char * base = tr_strndup(
			  tr_metainfoGetBasename (inf),
			  max_allowed_length
			  );
  char * filename = tr_strdup_printf ("%s" TR_PATH_DELIMITER_STR "%s.torrent",
                                      resume_dir, base);
  tr_free (base);
  return filename;
}

resume.c:
static char*
getResumeFilename (const tr_torrent * tor)
{
  const char * resume_dir = tr_getResumeDir (tor->session);
  size_t max_allowed_length = 255 - 1 - strlen(resume_dir);
  char * base = tr_strndup(
		  tr_metainfoGetBasename (tr_torrentInfo (tor)),
		  max_allowed_length
		  );

  char * filename = tr_strdup_printf ("%s" TR_PATH_DELIMITER_STR "%s.resume",
                                      resume_dir, base);
  tr_free (base);
  return filename;
}

Changes looks similar. I think it should be possible to extract them to common function into metainfo.c and just pass a required path...

**Comment by cfpp2p** [comment]
I am not exactly sure why you are trying to limit
the entire path + filename length.
You might eventually get something like that to function.
More immediately, you will need to account for the condition where
the subtractions involving `strlen(resume_dir)` result
in a negative. In `getTorrentFilename()` `torrent_dir`
would look better than `resume_dir`.

Although not resulting in pretty filenames,
the current solution present in trunk 2.9x works.
( see:  https://trac.transmissionbt.com/ticket/394 and https://github.com/transmission/transmission/commit/f5b26aa29bcf69ed7d7222bfed53f6c539f51453 )
If more descriptive filenames are desired
the fully functioning solution I presented,
with a little work, could be transferred.

**Comment by cfpp2p** [comment]
@Proga
I am not exactly sure why you are trying to limit
the entire path + filename length.
You might eventually get something like that to function.
More immediately, you will need to account for the condition where
the subtractions involving `strlen(resume_dir)` result
in a negative. In `getTorrentFilename()` `torrent_dir`
would look better than `resume_dir`.

Although not resulting in pretty filenames,
the current solution present in trunk 2.9x works.
( see:  https://trac.transmissionbt.com/ticket/394 and https://github.com/transmission/transmission/commit/f5b26aa29bcf69ed7d7222bfed53f6c539f51453 )
If more descriptive filenames are desired
the fully functioning solution I presented,
with a little work, could be transferred.

**Comment by Proga** [comment]
My fault: copy -paste.
Off cause the getTorrentFilename should have torrent dir.

I just found out that on my system the absolute path matter. 
So, even with the fixed char* tr_metainfoGetBasename(tr_info const* inf),
I still was getting "File name too long."
I use old Debian squeeze, because of the old hardware.

I will try to pull out the trunk and test it...

**Comment by nevn** [comment]
Ran into this bug today. Are efforts still underway to fix this?

**Comment by kov-serg** [comment]
try this script: https://pastebin.com/raw/kGH8UFHi to build it from source.

**Comment by Fitap** [comment]
Here one user more with the same issue.
I run Gentoo and trying to DL magnet links, ordinary links not tested.
Please, let me know if I send some log.

My best.

**Comment by diman82** [comment]
The only workaround is downloading a torrent file (NOT magnet linking) and manually trimming the long name.

**Comment by kiplingw** [comment]
That actually unfortunately doesn't always work. Sometimes even when trimming the long name, be it the torrent file name itself, or any of the stuff it downloads, you can still run into this problem.

**Comment by Alkaris** [comment]
A work around to this issue until this is properly fixed is to edit the
torrent name, but you have to do stupid hexadecimal conversions from text
to HTML hexadecimal format to replace the name of the torrent to work
around the "Filename too long" issue. Look for the part where the torrent
file name starts, and where it ends, and just replace that string with a
shorter file name.

**Comment by cfpp2p** [comment]
You can't just edit a .torrent metadata file **_name_**. The hash will change and the torrent will no longer work.

**Comment by diman82** [comment]
@cfpp2p No one was talking about .torrent metadata content, but about the filename.

**Comment by cfpp2p** [comment]
The title of this issue is:

> Error: Unable to save **_resume_** file: File name too long

transmission saves the **_resume_** file based on the name given in the info dict name field or when first getting magnet link  the name in the magnet link, then to the info dict name field once acquired the complete metadata.

The given name of the **_resume_** file is not at all resolved from the name of the   **.** torrent file.

**_resume_** file name problems are fixed in my fork via:
https://github.com/cfpp2p/transmission/commit/bf1d8bb20f41ec0963c128b4368b820d39d19702#diff-d54a64807eeb84d2c1ffec36a2dd76c1
https://github.com/cfpp2p/transmission/commit/5e660aed911c349165ca16d1ea818c8cb4cefe42
https://github.com/cfpp2p/transmission/commit/5b7532feae2fe7db4955e8e2b1b63dec6b5bfb87

or in official trunk by https://github.com/transmission/transmission/commit/bb4741002f832a8f1046196830917462d7063862

**Comment by kiplingw** [comment]
Exactly. It's the resume file that's the problem and that's what's reflected in the error message. @cfpp2p, if you haven't already, please submit a pull request.

**Comment by Alkaris** [comment]
@cfpp2p to give you an example of how you edit the filename of a torrent of a magnet link, it will look something like this.

```HTML
magnet:?xt=urn:btih:BITTORRENT_INFO_HASH&dn=TORRENT_NAME_HERE&tr=TRACKERS_HERE
```

only editing after the `&dn=` and before the `&tr=` the `&dn=` of course means Download Name of the file, and the `&tr=` means Trackers.

In the Windows build you are limited to using certain characters in file names otherwise the client will return an error, so you cant use characters like colons in the torrent file name which is `%3A` in HTML encoded format, but you can use plus sign characters, just a heads up there if you need to rename a torrent file name.

**Comment by cfpp2p** [comment]
@Alkaris 
What is it exactly you are trying to example? Of course I know how about the structure of magnet links. That's why I was demonstrating as linked just above to https://github.com/cfpp2p/transmission/commit/bf1d8bb20f41ec0963c128b4368b820d39d19702#diff-d54a64807eeb84d2c1ffec36a2dd76c1   at
@@ -507,7 +507,10 @@ tr_metainfoParseImpl( const tr_session * session,

which programmatically 

> Fixed: "Unable to save resume file: File name too long" for magnet links with extremely long names.

The Windows specific character limitations are addressed by cleanFilename() at  https://github.com/cfpp2p/transmission/blob/cygwin/libtransmission/magnet.c#L154

**Comment by Alkaris** [comment]
It's pretty obvious what's been shown in my example. Because just so you
know, your commits here on GitHub don't apply to the pre-compiled binaries
for Windows, they're not automatically pushed to the pre-compiled binaries,
which is the part you probably didn't realise, because other people would
be going directly to the Transmission website and not downloading from the
GitHub repos for pre-compiled binaries, because the average user doesn't
download and compile stuff for Windows.

**Comment by cfpp2p** [comment]
OK. Already compiled **official** nightly Windows builds ( which include the fix that officially closed the issue  https://github.com/transmission/transmission/commit/bb4741002f832a8f1046196830917462d7063862  _Go back to using hash as base name for resume and torrent files_ )  are here:
https://build.transmissionbt.com/job/trunk-win32/lastBuild/arch=x86,label=pepito-win10/
https://build.transmissionbt.com/job/trunk-win32/arch=x64,label=pepito-win10/lastBuild/
https://build.transmissionbt.com/job/trunk-win32/
:)

**Comment by rzcat** [comment]
This bug still exists on official 2.94 (d8e60ee44f)
:(

**Comment by ashep** [comment]
Same issue in 2.94. Bug still exist.

**Comment by mikedld** [comment]
The milestone is set to 3.00. Why would you think that it's fixed in 2.94?..

**Comment by zhanginin** [comment]
Is it true this problem will be solved? Cause it looks like a problem with OS or file system. Btrfs and ext4's file name max length is 255 bytes, while NTFS is 255 characters(UTF16 characters ). The torrent name can be changed, but the file names in the torrent can't be changed. Some torrents are made with windows, file names not valid on Linux, am I right? It's an annoying problem.,especially when you are in China or Japan.

**Comment by Alkaris** [comment]
> Is it true this problem will be solved? Cause it looks like a problem with OS or file system. Btrfs and ext4's file name max length is 255 bytes, while NTFS is 255 characters(UTF16 characters ). The torrent name can be changed, but the file names in the torrent can't be changed. Some torrents are made with windows, file names not valid on Linux, am I right? It's an annoying problem.,especially when you are in China or Japan.

No, not at all, this isn't a filesystem character issue, and the standard unicode format is UTF-8 when naming files as it's widely supported and most used. If someone is using UTF-16 that's when it's gonna be messy for other people because all they will see is squares or some other character that will be displayed differently in UTF-8.

**Comment by vblanton** [comment]
Looks like this bug is closed. I'm still getting this on Transmission 2.94 with magnet link that is too long of a filename.

**Comment by one-quaker** [comment]
> Looks like this bug is closed. I'm still getting this on Transmission 2.94 with magnet link that is too long of a filename.

I confirm, bug still here

**Comment by uzvermode** [comment]
> > Looks like this bug is closed. I'm still getting this on Transmission 2.94 with magnet link that is too long of a filename.
> 
> I confirm, bug still here

Same here :(

**Comment by andrewmed** [comment]
same here with 2.94. why it is closed?

**Comment by psycholyzern** [comment]
At least rename the file. I am using RPC API and it would be great if I can rename the torrent.

**Comment by one-quaker** [comment]
Guys, who can fix this bug? How it cost? :)

**Comment by Alkaris** [comment]
@one-quaker Fix will be coming in version 3.0 milestone release. If you actually read the milestones https://github.com/transmission/transmission/milestone/2

**Comment by teror4uks** [comment]
@Alkaris workaround work nice https://github.com/transmission/transmission/issues/122#issuecomment-410665459

**Comment by XVilka** [comment]
The 3.0 milestone is empty already, but there is still no release, and a bug is still here... And judging by https://github.com/transmission/transmission/issues/318 it can take years to wait

**Comment by gomera** [comment]
After 2 years and a half, we still don't have an official release with a fix for this issue. I know that there is a workaround by editing the magnet link but this sadly makes me wonder if I should give it a try to other clients. :'(

**Comment by one-quaker** [comment]
sad but true, deluge works great in this case

**Comment by smopucilowski** [comment]
Hit this bug last night.

**Comment by kov-serg** [comment]
What transmission version? And what files in names in config dir
linux: find ~/.config/transmission
windows: dir /s /b "%appdata%/transmission"

**Comment by pgorod** [comment]
This magnet link fails for me on Windows with version 2.94

```
magnet:?xt=urn:btih:8ED644946AA19DFB4E4DC58C407B2B0CAA24D82B&dn=%5Bzooqle.com%5D%20Avengers%3A%20Endgame%20%282019%29%20%5BBluRay%5D%20%5B1080p%5D%20%5BYTS.LT%5D&tr=http://explodie.org:6969/announce&tr=http://announce.xxx-tracker.com:2710/announce&tr=https://bigfoot1942.sektori.org/announce&tr=https://bigfoot1942.sektori.org:443/announce&tr=http://open.acgtracker.com:1096/announce&xl=1686660690&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=http%3A%2F%2Fannounce.xxx-tracker.com%3A2710%2Fannounce&tr=http%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=https%3A%2F%2Fbigfoot1942.sektori.org%2Fannounce&tr=https%3A%2F%2Fbigfoot1942.sektori.org%3A443%2Fannounce
```

I guess it's the colon in the name...

I saw a zero-length file in `AppData\Local\transmission\Torrents` called `[zooqle.com] Avengers`

The error message on the UI said `Error: Unable to save resume file: unknown error`

I hope this helps debugging. Thanks.

**Comment by kov-serg** [comment]
It is simple in 2.9x branch no fix applied https://github.com/transmission/transmission/blob/2.9x/libtransmission/metainfo.c or https://github.com/transmission/transmission-releases/raw/master/transmission-2.94.tar.xz 
char* tr_metainfoGetBasename (const tr_info * inf) - is unchanged and contains this problem.

Why version with this problem is default for download this is the question.

So you have to use night build. https://build.transmissionbt.com/job/trunk-win32/
There is new version with char* tr_metainfoGetBasename(tr_info const* inf, enum tr_metainfo_basename_format format)

**Comment by Queuecumber** [comment]
It looks like the 3.0 release will probably never happen, is anyone even maintaining this anymore?

**Comment by dausruddin** [comment]
@Queuecumber maybe they are busy.
I compiled the program by myself and included some PR.
Currently it is running well excep that I have to use Web-UI from 2.94 because Web-Ui from 3.00 due to bugs.

At this point I would probably migrate to qBittorrent.

**Comment by gomera** [comment]
> @Queuecumber maybe they are busy.
> I compiled the program by myself and included some PR.
> Currently it is running well excep that I have to use Web-UI from 2.94 because Web-Ui from 3.00 due to bugs.
> 
> At this point I would probably migrate to qBittorrent.

@dausruddin I've been using qBittorrent for the last 3 months and I am more than happy with it. Who knows, maybe in the future I will give transmission another chance.

**Comment by diman82** [comment]
> As in my example above ([#122 (comment)](https://github.com/transmission/transmission/issues/122#issuecomment-270463467)) you could just text edit manually the name portion of any magnet (begins with **&dn=**) down to a short(er) length. Or you can patch metainfo.c at **_maybe get the display name_**. It's only a temporary display name until the real metadata is acquired.
> 
> ```
>           /* maybe get the display name */
>           if (tr_variantDictFindStr (d, TR_KEY_display_name, &str, &len))
>             {
>               tr_free (inf->name);
>               tr_free (inf->originalName);
>               if (len > 50)
>                 {
>                   inf->name = tr_strndup (str, 50);
>                   inf->originalName = tr_strndup (str, 50);
>                 }
>               else
>                 {
>                  inf->name = tr_strndup (str, len);
>                  inf->originalName = tr_strndup (str, len);
>                 }
>             }
> ```
> 
> ref: [cfpp2p/transmission@bf1d8bb#diff-d54a64807eeb84d2c1ffec36a2dd76c1](https://github.com/cfpp2p/transmission/commit/bf1d8bb20f41ec0963c128b4368b820d39d19702#diff-d54a64807eeb84d2c1ffec36a2dd76c1)

Worked like a charm (problem is due to a very long Cyrillic description)

**Comment by luntik2012** [comment]
the same issue in 3.00 with magnet and torrent file

magnet:?xt=urn:btih:093123D8D074A124E390340B17EE31B60FDCB4C4&tr=http%3A%2F%2Fbt4.t-ru.org%2Fann%3Fmagnet&dn=%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%81%D1%82%D0%B0%20-%20Gamma%2C%20Helm%2C%20Johnson%2C%20Vlissides%2F%D0%93%D0%B0%D0%BC%D0%BC%D0%B0%2C%20%D0%A5%D0%B5%D0%BB%D0%BC%2C%20%D0%94%D0%B6%D0%BE%D0%BD%D1%81%D0%BE%D0%BD%2C%20%D0%92%D0%BB%D0%B8%D1%81%D1%81%D0%B8%D0%B4%D0%B5%D1%81%20-%20Design%20Patterns.%20Elements%20of%20Reusable%20Object-Oriented%20Soft

**Comment by appotry** [comment]
this bug is not fixed!

Please fixed this bug!

master/libtransmission/metainfo.c
===============
static char* metainfoGetBasenameNameAndPartialHash(tr_info const* inf)
{
    char const* name = inf->originalName;
    size_t const name_len = strlen(name);
    char* ret = tr_strdup_printf("%s.%16.16s", name, inf->hashString);

    for (size_t i = 0; i < name_len; ++i)
    {
        if (char_is_path_separator(ret[i]))
        {
            ret[i] = '_';
        }
    }

    return ret;
}

**Comment by ldesousa** [comment]
Having this issue with transmission-daemon 2.94 on Ubuntu 20.04. The issue was closed in 2017, prior to the 2.94 release. Was the fix not included in that release? Could someone please clarify? Thank you.

FYI @mikedld

**Comment by mikedld** [comment]
@ldesousa, milestone is set to 3.00.

**Comment by ldesousa** [comment]
@mikedld I just upgraded transmission-daemon to release 3.00. However the error remains and transmission is still unable to resume the download. I installed from the transmission PPA for Ubuntu:

```
$ apt policy transmission-daemon
transmission-daemon:
  Installed: 3.00-1ubuntu1~20.04.1
  Candidate: 3.00-1ubuntu1~20.04.1
  Version table:
 *** 3.00-1ubuntu1~20.04.1 500
        500 http://ppa.launchpad.net/transmissionbt/ppa/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     2.94-2ubuntu3 500
        500 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```

Could there be something wrong with the release available from this PPA?

**Comment by imkyaky** [comment]
after 5 years , problem still exists. Transmission 3.00 (bb6b5a062e)

**Comment by kov-serg** [comment]
It's funny. I think it because there is no tests for this issue.
https://github.com/transmission/transmission/blob/3.00/libtransmission/metainfo.c#L39
it should be changed to something like this:
```
static char* metainfoGetBasenameNameAndPartialHash(tr_info const* inf)
{
    enum { name_length_limit=64 }; // 219
    char *shortName, *cleanName;
    char const* name = inf->originalName;
    size_t const name_len = strlen(name);

    shortName = tr_strndup(name, name_length_limit);
    cleanName = tr_utf8clean(shortName, -1);
    char* ret = tr_strdup_printf("%s.%16.16s", cleanName, inf->hashString);
    tr_free(shortName);

    for (char *p=ret;*p;p++)
    {
        if (char_is_path_separator(*p))
        {
            *p = '_';
        }
    }

    return ret;
}
```

**Comment by antivirtel** [comment]
@mikedld can you please reopen the ticket at least? I see you closed it, but it's clearly not fixed in 3.0 either.

**Comment by gilad905** [comment]
> As in my example above ([#122 (comment)](https://github.com/transmission/transmission/issues/122#issuecomment-270463467)) you could just text edit manually the name portion of any magnet (begins with **&dn=**) down to a short(er) length. 

@cfpp2p 
Note on this - I've tried manually shortening the value of `dn` in the magnet link and adding the torrent via the webUI, it still doesn't help.
After fetching metadata for the torrent, torrent name (in webUI) changes to the original `dn` value. On pausing the torrent, `File name too long` still pops up.

**Comment by gelin** [comment]
An example of magnet link which causes the failure: magnet:?xt=urn:btih:04299340083CD357431818B18C7AB8A1C104677E&tr=http%3A%2F%2Fbt.t-ru.org%2Fann%3Fmagnet&dn=%D0%9F%D0%BE%D0%BB%D1%91%D1%82%20%D0%B4%D1%80%D0%B0%D0%BA%D0%BE%D0%BD%D0%BE%D0%B2%20%2F%20The%20Flight%20of%20Dragons%20(%D0%94%D0%B6%D1%83%D0%BB%D0%B7%20%D0%91%D0%B0%D1%81%D1%81%2C%20%D0%90%D1%80%D1%82%D1%83%D1%80%20%D0%A0%D0%B0%D0%BD%D0%BA%D0%B8%D0%BD%20%D0%BC%D0%BB.)%20%5B1982%2C%20%D0%A1%D0%A8%D0%90%2C%20%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%2C%20%D1%84%D1%8D%D0%BD%D1%82%D0%B5%D0%B7%D0%B8%2C%20%D0%BC%D0%B5%D0%BB%D0%BE%D0%B4%D1%80%D0%B0%D0%BC%D0%B0%2C%20%D0%BF%D1%80%D0%B8%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%2C%20%D1%81%D0%B5%D0%BC%D0%B5%D0%B9%2C%20BDRip%201080p%5D%20MVO

Doesn't work both with 2.84 and 2.94.

**Comment by mikedld** [comment]
@gelin, milestone for this issue is set to 3.00.

**Comment by ckerr** [comment]
The torrent linked two comments up appears to be content that is not in the public domain. User banned + comment deleted.

**Comment by vird** [comment]
Partially helps
~/.config/transmission/settings.json
rename-partial-files:false

**Comment by pugzly** [comment]
It's strange ~7 years later Transmission still struggles with long file names.
Due to my partition being encrypted, length of file names is limited. Renaming torrents (files, and directories) helps only partially to shorten those, download usually still fails after first few megabytes downloaded, with error message:
"Error: Unable to save resume file: File name too long"
And I need to manually force it to resume, again and again, every few megabytes. Seems like the only viable workaround is to use Deluge.

**Comment by kov-serg** [comment]
https://www.qbittorrent.org/

**Comment by chrdev** [comment]
Jeez! I've done my own emergency fix. Tested working on v4.0.6.

This patch detects a filename longer than 255, truncates it as needed, append file-unique-id string to avoid name collision, then append extension name back to the path, and support incomplete file ".part" suffix.

```diff
diff --git a/libtransmission/file-posix.cc b/libtransmission/file-posix.cc
index 82840bfd..3d00b006 100644
--- a/libtransmission/file-posix.cc
+++ b/libtransmission/file-posix.cc
@@ -261,6 +261,46 @@ std::string_view tr_sys_path_basename(std::string_view path, tr_error** /*error*
     return std::empty(path) ? "/"sv : path;
 }
 
+bool tr_sys_path_limit_filename(std::string& subpath, std::string_view suffix, size_t extra)
+{
+    constexpr size_t kMaxExt = 9; // Includes dot. Keeps ".backup", ".original".
+
+    auto basename_pos = subpath.find_last_of('/');
+    if (basename_pos == std::string::npos) basename_pos = 0;
+    else if (basename_pos == subpath.size() - 1) return false; // subpath ends with '/', so it's not a file.
+    else ++basename_pos;
+
+    if (auto basename_len = subpath.size() - basename_pos; basename_len + extra < 256) return false;
+
+    auto ext_pos = subpath.find_last_of('.');
+    if (ext_pos != std::string::npos)
+    {
+        if (ext_pos <= basename_pos)
+        {
+            ext_pos = std::string::npos;
+        }
+        else if (auto ext_len = subpath.size() - ext_pos; ext_len > kMaxExt)
+        {
+            ext_pos = std::string::npos;
+        }
+    }
+    auto const ext = ext_pos == std::string::npos ? ""s : std::string{ subpath.cbegin() + ext_pos, subpath.cend() };
+
+    auto cut_pos = basename_pos + 255 - ext.size() - suffix.size() - extra;
+	// Avoid cutting at the middle of a UTF-8 character.
+    for (auto iter = subpath.cbegin() + cut_pos; iter > subpath.cbegin() + basename_pos; --iter)
+    {
+        if ((*iter & 0xC0) == 0x80) --cut_pos;
+        else break;
+    }
+
+    subpath.erase(cut_pos);
+    subpath.append(suffix);
+    subpath.append(ext);
+
+    return true;
+}
+
 // This function is adapted from Node.js's path.posix.dirname() function,
 // which is copyrighted by Joyent, Inc. and other Node contributors
 // and is distributed under MIT (SPDX:MIT) license.
diff --git a/libtransmission/file-win32.cc b/libtransmission/file-win32.cc
index dc562e4b..fefa89e8 100644
--- a/libtransmission/file-win32.cc
+++ b/libtransmission/file-win32.cc
@@ -581,6 +581,12 @@ std::string_view tr_sys_path_basename(std::string_view path, tr_error** error)
     return !std::empty(path) ? path : "/"sv;
 }
 
+// Not implemented. May not need to at all. Return false to indicate subpath not changed.
+bool tr_sys_path_limit_filename(std::string& subpath, std::string_view suffix, size_t extra)
+{
+    return false;
+}
+
 [[nodiscard]] static bool isWindowsDeviceRoot(char ch) noexcept
 {
     return isalpha(static_cast<int>(ch)) != 0;
diff --git a/libtransmission/file.h b/libtransmission/file.h
index 6d19340f..66e29853 100644
--- a/libtransmission/file.h
+++ b/libtransmission/file.h
@@ -233,6 +233,21 @@ std::string tr_sys_path_resolve(std::string_view path, struct tr_error** error =
  */
 std::string_view tr_sys_path_basename(std::string_view path, struct tr_error** error = nullptr);
 
+/**
+* @brief Limit filename length to 255.
+*        Truncate basename at tail, append suffix, then append extension back.
+*        The resultant subpath length is limited to (255 - extra).
+*
+* @param[in,out] subpath Only the basename part may be changed.
+* @param[in] suffix Normally a file ID string to help avoid filename collision.
+* @param[in] extra Extra bytes to reserve, for ".part", or 0 if not needed.
+*
+* @return Whether subpath is changed.
+*         If subpath basename too long, then subpath is changed, return true.
+*         If basename length was less than (255 - extra), return false.
+*/
+bool tr_sys_path_limit_filename(std::string& subpath, std::string_view suffix, size_t extra);
+
 /**
  * @brief Portability wrapper for `dirname()`.
  *
diff --git a/libtransmission/inout.cc b/libtransmission/inout.cc
index 458cb05b..e99e9b48 100644
--- a/libtransmission/inout.cc
+++ b/libtransmission/inout.cc
@@ -72,7 +72,7 @@ enum class IoMode
     Write
 };
 
-bool getFilename(tr_pathbuf& setme, tr_torrent const* tor, tr_file_index_t file_index, IoMode io_mode)
+bool getFilename(tr_pathbuf& setme, tr_torrent* tor, tr_file_index_t file_index, IoMode io_mode)
 {
     if (auto found = tor->findFile(file_index); found)
     {
@@ -89,7 +89,17 @@ bool getFilename(tr_pathbuf& setme, tr_torrent const* tor, tr_file_index_t file_
     // Let's figure out where it goes so that we can create it.
     auto const base = tor->currentDir();
     auto const suffix = tor->session->isIncompleteFileNamingEnabled() ? tr_torrent_files::PartialFileSuffix : ""sv;
-    setme.assign(base, '/', tor->fileSubpath(file_index), suffix);
+
+    std::string subpath{ tor->fileSubpath(file_index) };
+    auto const idstr = fmt::format("_{:x}-{}", file_index, tor->infoHashString()); // Avoid filename collision with best efforts.
+    auto const changed = tr_sys_path_limit_filename(subpath, idstr, suffix.size());
+    setme.assign(base, '/', subpath, suffix);
+    if (changed)
+    {
+        tor->setFileSubpath(file_index, subpath);
+        tor->setDirty();
+		tor->markChanged();
+    }
     return true;
 }
```

**Comment by chrdev** [comment]
Thanks!

The patched version has been running on my machine for weeks without a problem.

But I merely skimmed the codebase and planted the patch, I don't get the whole picture. For example, I don't know what these two lines actually do, I only tried to mimic a user's renaming operation:
```
tor->setDirty();
tor->markChanged();
```
Besides, the patch may need some modifications to meet the production quality. So, I don't dare to summit it as a PR.

At this point, a user has to patch and compile for him/herself.

**Comment by ppenguin** [comment]
> The patched version has been running on my machine for weeks without a problem.

Thanks, I built a container with the patch and it has been running without issue too for more than a week now...

> But I merely skimmed the codebase and planted the patch, I don't get the whole picture. For example, I don't know what these two lines actually do, I only tried to mimic a user's renaming operation:
> 
> ```
> tor->setDirty();
> tor->markChanged();
> ```
> 
> Besides, the patch may need some modifications to meet the production quality. So, I don't dare to summit it as a PR.

I understand. I've no experience with this code base, but even if it may not meet the quality requirements, maybe a draft PR with "help wanted" could also go some way. Just an idea.

I saw somewhere that the author basically says that "file name too long" is an edge case, but I looked it up and it's not true, most production filesystems have a _basename_ limit of 255 unicode characters, only the total path name is longer on the "good ones". Maybe most torrents don't have ridicilously long filenames though, but still a good case to cover I'd say.

**Comment by FFatTiger** [comment]
> Jeez! I've done my own emergency fix. Tested working on v4.0.6.
> 
> This patch detects a filename longer than 255, truncates it as needed, append file-unique-id string to avoid name collision, then append extension name back to the path, and support incomplete file ".part" suffix.
> 
> diff --git a/libtransmission/file-posix.cc b/libtransmission/file-posix.cc
> index 82840bfd..3d00b006 100644
> --- a/libtransmission/file-posix.cc
> +++ b/libtransmission/file-posix.cc
> @@ -261,6 +261,46 @@ std::string_view tr_sys_path_basename(std::string_view path, tr_error** /*error*
>      return std::empty(path) ? "/"sv : path;
>  }
>  
> +bool tr_sys_path_limit_filename(std::string& subpath, std::string_view suffix, size_t extra)
> +{
> +    constexpr size_t kMaxExt = 9; // Includes dot. Keeps ".backup", ".original".
> +
> +    auto basename_pos = subpath.find_last_of('/');
> +    if (basename_pos == std::string::npos) basename_pos = 0;
> +    else if (basename_pos == subpath.size() - 1) return false; // subpath ends with '/', so it's not a file.
> +    else ++basename_pos;
> +
> +    if (auto basename_len = subpath.size() - basename_pos; basename_len + extra < 256) return false;
> +
> +    auto ext_pos = subpath.find_last_of('.');
> +    if (ext_pos != std::string::npos)
> +    {
> +        if (ext_pos <= basename_pos)
> +        {
> +            ext_pos = std::string::npos;
> +        }
> +        else if (auto ext_len = subpath.size() - ext_pos; ext_len > kMaxExt)
> +        {
> +            ext_pos = std::string::npos;
> +        }
> +    }
> +    auto const ext = ext_pos == std::string::npos ? ""s : std::string{ subpath.cbegin() + ext_pos, subpath.cend() };
> +
> +    auto cut_pos = basename_pos + 255 - ext.size() - suffix.size() - extra;
> +	// Avoid cutting at the middle of a UTF-8 character.
> +    for (auto iter = subpath.cbegin() + cut_pos; iter > subpath.cbegin() + basename_pos; --iter)
> +    {
> +        if ((*iter & 0xC0) == 0x80) --cut_pos;
> +        else break;
> +    }
> +
> +    subpath.erase(cut_pos);
> +    subpath.append(suffix);
> +    subpath.append(ext);
> +
> +    return true;
> +}
> +
>  // This function is adapted from Node.js's path.posix.dirname() function,
>  // which is copyrighted by Joyent, Inc. and other Node contributors
>  // and is distributed under MIT (SPDX:MIT) license.
> diff --git a/libtransmission/file-win32.cc b/libtransmission/file-win32.cc
> index dc562e4b..fefa89e8 100644
> --- a/libtransmission/file-win32.cc
> +++ b/libtransmission/file-win32.cc
> @@ -581,6 +581,12 @@ std::string_view tr_sys_path_basename(std::string_view path, tr_error** error)
>      return !std::empty(path) ? path : "/"sv;
>  }
>  
> +// Not implemented. May not need to at all. Return false to indicate subpath not changed.
> +bool tr_sys_path_limit_filename(std::string& subpath, std::string_view suffix, size_t extra)
> +{
> +    return false;
> +}
> +
>  [[nodiscard]] static bool isWindowsDeviceRoot(char ch) noexcept
>  {
>      return isalpha(static_cast<int>(ch)) != 0;
> diff --git a/libtransmission/file.h b/libtransmission/file.h
> index 6d19340f..66e29853 100644
> --- a/libtransmission/file.h
> +++ b/libtransmission/file.h
> @@ -233,6 +233,21 @@ std::string tr_sys_path_resolve(std::string_view path, struct tr_error** error =
>   */
>  std::string_view tr_sys_path_basename(std::string_view path, struct tr_error** error = nullptr);
>  
> +/**
> +* @brief Limit filename length to 255.
> +*        Truncate basename at tail, append suffix, then append extension back.
> +*        The resultant subpath length is limited to (255 - extra).
> +*
> +* @param[in,out] subpath Only the basename part may be changed.
> +* @param[in] suffix Normally a file ID string to help avoid filename collision.
> +* @param[in] extra Extra bytes to reserve, for ".part", or 0 if not needed.
> +*
> +* @return Whether subpath is changed.
> +*         If subpath basename too long, then subpath is changed, return true.
> +*         If basename length was less than (255 - extra), return false.
> +*/
> +bool tr_sys_path_limit_filename(std::string& subpath, std::string_view suffix, size_t extra);
> +
>  /**
>   * @brief Portability wrapper for `dirname()`.
>   *
> diff --git a/libtransmission/inout.cc b/libtransmission/inout.cc
> index 458cb05b..e99e9b48 100644
> --- a/libtransmission/inout.cc
> +++ b/libtransmission/inout.cc
> @@ -72,7 +72,7 @@ enum class IoMode
>      Write
>  };
>  
> -bool getFilename(tr_pathbuf& setme, tr_torrent const* tor, tr_file_index_t file_index, IoMode io_mode)
> +bool getFilename(tr_pathbuf& setme, tr_torrent* tor, tr_file_index_t file_index, IoMode io_mode)
>  {
>      if (auto found = tor->findFile(file_index); found)
>      {
> @@ -89,7 +89,17 @@ bool getFilename(tr_pathbuf& setme, tr_torrent const* tor, tr_file_index_t file_
>      // Let's figure out where it goes so that we can create it.
>      auto const base = tor->currentDir();
>      auto const suffix = tor->session->isIncompleteFileNamingEnabled() ? tr_torrent_files::PartialFileSuffix : ""sv;
> -    setme.assign(base, '/', tor->fileSubpath(file_index), suffix);
> +
> +    std::string subpath{ tor->fileSubpath(file_index) };
> +    auto const idstr = fmt::format("_{:x}-{}", file_index, tor->infoHashString()); // Avoid filename collision with best efforts.
> +    auto const changed = tr_sys_path_limit_filename(subpath, idstr, suffix.size());
> +    setme.assign(base, '/', subpath, suffix);
> +    if (changed)
> +    {
> +        tor->setFileSubpath(file_index, subpath);
> +        tor->setDirty();
> +        tor->markChanged();
> +    }
>      return true;
>  }

Hi,

I've been struggling with the "filename too long" bug for quite some time now. I attempted to build a new Docker image using your diff, and while I learned a lot in the process, I ultimately found that constructing and publishing a fixed version of the Transmission Docker image is a bit too complex for me. I would greatly appreciate it if you could consider releasing a Docker image with this fix. If this request is inconvenient or inappropriate, please feel free to disregard it, and I'll continue working on it on my own. Thank you very much for your time and effort!

**Comment by ppenguin** [comment]
> I've been struggling with the "filename too long" bug for quite some time now. I attempted to build a new Docker image using your diff, and while I learned a lot in the process, I ultimately found that constructing and publishing a fixed version of the Transmission Docker image is a bit too complex for me. I would greatly appreciate it if you could consider releasing a Docker image with this fix.

You could use [mine](docker.io/ppenguin/transmission-openvpn:4.0.6-lfn) if you have use for the openvpn integration, or get some inspiration from [the repo that produces this image](https://github.com/ppenguin/docker-transmission-openvpn/tree/long-filenames-patch)

No functionality or maintenance guarantees, it's just an image with the patch applied.

**Comment by FFatTiger** [comment]
> > I've been struggling with the "filename too long" bug for quite some time now. I attempted to build a new Docker image using your diff, and while I learned a lot in the process, I ultimately found that constructing and publishing a fixed version of the Transmission Docker image is a bit too complex for me. I would greatly appreciate it if you could consider releasing a Docker image with this fix.
> 
> You could use [mine](docker.io/ppenguin/transmission-openvpn:4.0.6-lfn) if you have use for the openvpn integration, or get some inspiration from [the repo that produces this image](https://github.com/ppenguin/docker-transmission-openvpn/tree/long-filenames-patch)
> 
> No functionality or maintenance guarantees, it's just an image with the patch applied.

Hi [@chrdev](https://github.com/chrdev) and [@ppenguin](https://github.com/ppenguin),

Thank you both for your contributions and for providing a solution to the long filename issue in Transmission! 🎉

I have forked the project and implemented the fix in my own repository:
🔗 [FFatTiger/docker-transmission](https://github.com/FFatTiger/docker-transmission)

Additionally, I have built and deployed a Docker image incorporating this fix. It is now available on Docker Hub:
🔗 My Transmission Docker Image

I appreciate your work and the time you took to share the solution with the community. Hopefully, this will help more users who face the same issue.

Thanks again! 🚀
