### ISSUE TITLE
Error: Please Verify Local Data! Piece #xxxx is corrupt

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#2207]
- Transmission v.3.00+1459220b5b
- macOS v.12.0.1 (21A559)

For the last 1.5 to 2 weeks I have been noticing the error:

<img width="662" alt="Screen Shot 2021-11-23 at 14 37 33 2" src="https://user-images.githubusercontent.com/62497891/143038057-abc656b9-ead6-4c2b-9611-56ad20dde148.png">

**Comment by djcristi** [comment]
same here, since the last 2-3 commits. m1 , macos 12

**Comment by djcristi** [comment]
seems fixed in 06090f1

**Comment by al3xandru** [comment]
Seeing this in 2977636d58

**Comment by Oleg-Chashko** [comment]
<img width="662" alt="Screen Shot 2021-12-06 at 13 02 11" src="https://user-images.githubusercontent.com/62497891/144859225-bbb2fb65-b393-4379-8f8a-ac8cf5f52f15.png">
<img width="702" alt="Screen Shot 2021-12-06 at 13 02 54" src="https://user-images.githubusercontent.com/62497891/144859238-e6c28eb6-bd3d-4ef0-92a5-cd20828df659.png">

**Comment by djcristi** [comment]
tried now 37a8046 , and it seems fixed.

**Comment by Oleg-Chashko** [comment]
@djcristi 
No, it's not fixed yet. (v.3.00+37a8046ed5)

<img width="662" alt="Screen Shot 3 00+ (37a8046ed5)" src="https://user-images.githubusercontent.com/62497891/146547652-f653ac4c-9d12-4d69-b871-f15f97850c51.png">

**Comment by djcristi** [comment]
are you sure you are using latest build ? i tried with many torrents and it works now.

**Comment by Oleg-Chashko** [comment]
_are you sure you are using latest build ?_

Yes.
<img width="548" alt="Screen Shot 2021-12-17 at 14 46 10" src="https://user-images.githubusercontent.com/62497891/146553940-341cf642-6913-42c7-89f4-285a2a11fd06.png">

<img width="776" alt="Screen Shot 2021-12-17 at 14 49 01" src="https://user-images.githubusercontent.com/62497891/146554102-f6bbe391-14da-44c6-8ec9-9870e297b6eb.png">

**Comment by djcristi** [comment]
sorry my fault, i have 2 apps installed, and opened by mistake an old fork which does not hava that issue.

**Comment by pjgois** [comment]
Same here! In the last builds I tried (the latest was from the day before yesterday) most downloads result in corrupted files.

**Comment by Oleg-Chashko** [comment]
Closed the issue. Since it may have already been fixed. In the near future, the problem was not noticed.

**Comment by djcristi** [comment]
stll there but only showing message, download continues/finishes.

**Comment by catadropa** [comment]
Can this issue be reopened? I see it on my git-build current as of 11 Feb. The torrent finishes but is red and I need to verify local data to get it to throw away a few pieces, refetch those pieces, and complete properly.

**Comment by Oleg-Chashko** [comment]
Issue the reopened.

**Comment by catadropa** [comment]
It hasn't happened again for a while, but it just happened again. I have 5 active torrents downloading (~5 MB/s total) and one of them at 15% done has already reported a corrupt piece. I don't think it's enough to trigger this bug to just have one active torrent at high rate because I've been doing that off and on for 2 weeks no problem. Today the difference seems to be the multiple torrents. I haven't updated my build at all.

**Comment by catadropa** [comment]
Is there a possibility that the torrent pieces are getting confused between the actively-downloading torrents or misassembled? Or is it just a poisoned or otherwise bad peer sending bad data? Once we have this failed piece, shouldn't it be discarded automatically? The log's only error-level entry: "Piece 1267, which was just downloaded, failed its checksum test"
Looking at that particular torrent (without running Verify Local Data) now that it's 43% done, it says:
Downloaded 3.33 GB (+4.19 MB discarded after failed checksum)

So I wonder if piece 1267 is the same 4.19 MB discarded? Or is bad data only sometimes getting discarded? Or reporting it as bad and discarded, but forgetting to actually discard the data?

**Comment by Oleg-Chashko** [comment]
Closed the issue. Since it may have already been fixed. In the near future, the problem was not noticed.
