### ISSUE TITLE
[49b0df8] transmission-gtk: 'too many open files'

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#3677]
I prefer transmission-qt but mostly use transmission-gtk (since 1+ years) because of transmission-qt problems (reported).  Transmission-gtk has its own problems.  On GNU/Linux sometime after 3,000 torrents transmission-gtk starts saying 'local error: too many open files'.  Someone on IRC said increase ulimit so I run a transmission script that first does 'sudo -i ulimit -n 8192' then runs transmission then resets ulimit default.  If I used UNIX/*BSD/*Solaris/IllumOS I could have higher non-root uliimit but UNIX operating systems (OS, despite better/stabler design/kernel) lack some drivers (graphics cards) and software (Pale Moon, the only remaining true 2000s-style web browser).

**Comment by dchmelik** [comment]
Seems most likely fixed in recent commits.

**Comment by chaseholden** [comment]
This is happening again w current build b49129dfa6  #8345

**Comment by ckerr** [comment]
I _think_ that #4534 / b47c34726b25e438620505d5e17ff018b0f7cc1a fixes this and haven't seen it happen since that landed.

Is anyone else seeing this post-b47c34726b25e438620505d5e17ff018b0f7cc1a?

**Comment by gaborhargitai-kh** [comment]
Just tried the latest nightly [Transmission-2b89ee508b](https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/artifact/release/Transmission-2b89ee508b.dmg) with 145 torrent files - it still happens, sadly.

**Comment by drummingdemon** [comment]
Just tried the latest nightly [Transmission-2b89ee508b](https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/artifact/release/Transmission-2b89ee508b.dmg) with 145 torrent files - it still happens, sadly.

**Comment by ckerr** [comment]
Well, bah.

Thanks for the checkin @drummingdemon :bowing_man:

**Comment by mikedld** [comment]
Out of cusiosity, what are those descriptors spent on (in categories, w/o specifics)? Checking out `lsof` output might give some new ideas.

**Comment by InsaneKnight** [comment]
@mikedld
This issue hits my transmission-daemon built from 3bc1a1b. A piece of the output of `lsof -np <pid of transmission-daemon>` looks like this:
```
COMMAND       PID USER   FD      TYPE             DEVICE   SIZE/OFF      NODE NAME
transmiss 2327726 user  cwd       DIR              253,1       4096         2 /
transmiss 2327726 user  rtd       DIR              253,1       4096         2 /
transmiss 2327726 user  txt       REG              0,179   71721464        15 /usr/local/bin/transmission-daemon
transmiss 2327726 user  mem       REG              253,1      60328    932971 /usr/lib/x86_64-linux-gnu/libresolv.so.2
transmiss 2327726 user  mem       REG              253,1      22448    919072 /usr/lib/x86_64-linux-gnu/libkeyutils.so.1
transmiss 2327726 user  mem       REG              253,1      43480    919180 /usr/lib/x86_64-linux-gnu/libffi.so.8
transmiss 2327726 user  mem       REG              253,1     137376    922223 /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1
transmiss 2327726 user  mem       REG              253,1     113392    921956 /usr/lib/x86_64-linux-gnu/libsasl2.so.2
transmiss 2327726 user  mem       REG              253,1      52224    928386 /usr/lib/x86_64-linux-gnu/libkrb5support.so.0
transmiss 2327726 user  mem       REG              253,1      18344    925744 /usr/lib/x86_64-linux-gnu/libcom_err.so.2
transmiss 2327726 user  mem       REG              253,1     183048    926397 /usr/lib/x86_64-linux-gnu/libk5crypto.so.3
transmiss 2327726 user  mem       REG              253,1     888080    926404 /usr/lib/x86_64-linux-gnu/libkrb5.so.3
transmiss 2327726 user  mem       REG              253,1    1261376    922039 /usr/lib/x86_64-linux-gnu/libp11-kit.so.0
transmiss 2327726 user  mem       REG              253,1     529216    919862 /usr/lib/x86_64-linux-gnu/libgmp.so.10
transmiss 2327726 user  mem       REG              253,1     292856    928632 /usr/lib/x86_64-linux-gnu/libhogweed.so.6
transmiss 2327726 user  mem       REG              253,1     157768    929470 /usr/lib/x86_64-linux-gnu/libgpg-error.so.0
transmiss 2327726 user  mem       REG              253,1    1792040    935336 /usr/lib/x86_64-linux-gnu/libunistring.so.2
transmiss 2327726 user  mem       REG              253,1    2193144    917852 /usr/lib/x86_64-linux-gnu/libgnutls.so.30
transmiss 2327726 user  mem       REG              253,1      83968    919146 /usr/lib/x86_64-linux-gnu/libtasn1.so.6
transmiss 2327726 user  mem       REG              253,1     121280    924953 /usr/lib/x86_64-linux-gnu/libz.so.1
transmiss 2327726 user  mem       REG              253,1      63832    922222 /usr/lib/x86_64-linux-gnu/liblber-2.5.so.0
transmiss 2327726 user  mem       REG              253,1     380432    937083 /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0
transmiss 2327726 user  mem       REG              253,1     334584    927963 /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
transmiss 2327726 user  mem       REG              253,1     317544    922621 /usr/lib/x86_64-linux-gnu/libnettle.so.8
transmiss 2327726 user  mem       REG              253,1     260552    927289 /usr/lib/x86_64-linux-gnu/libssh2.so.1
transmiss 2327726 user  mem       REG              253,1     122280    939427 /usr/lib/x86_64-linux-gnu/librtmp.so.1
transmiss 2327726 user  mem       REG              253,1     198776    920951 /usr/lib/x86_64-linux-gnu/libidn2.so.0
transmiss 2327726 user  mem       REG              253,1     186800    927205 /usr/lib/x86_64-linux-gnu/libnghttp2.so.14
transmiss 2327726 user  mem       REG              253,1     751840    923371 /usr/lib/x86_64-linux-gnu/libzstd.so.1
transmiss 2327726 user  mem       REG              253,1    1332480    940451 /usr/lib/x86_64-linux-gnu/libgcrypt.so.20
transmiss 2327726 user  mem       REG              253,1    1922136    929224 /usr/lib/x86_64-linux-gnu/libc.so.6
transmiss 2327726 user  mem       REG              253,1    2190440    923711 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
transmiss 2327726 user  mem       REG              253,1      47264    926840 /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1
transmiss 2327726 user  mem       REG              253,1     149952    919640 /usr/lib/x86_64-linux-gnu/liblz4.so.1
transmiss 2327726 user  mem       REG              253,1     190456    926308 /usr/lib/x86_64-linux-gnu/liblzma.so.5
transmiss 2327726 user  mem       REG              253,1     907784    929675 /usr/lib/x86_64-linux-gnu/libm.so.6
transmiss 2327726 user  mem       REG              253,1     665336    921668 /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
transmiss 2327726 user  mem       REG              253,1    4697368    918606 /usr/lib/x86_64-linux-gnu/libcrypto.so.3
transmiss 2327726 user  mem       REG              253,1      14480    932487 /usr/lib/x86_64-linux-gnu/libpthread.so.0
transmiss 2327726 user  mem       REG              253,1      47288    924397 /usr/lib/x86_64-linux-gnu/libcap.so.2
transmiss 2327726 user  mem       REG              253,1     125312    918543 /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
transmiss 2327726 user  mem       REG              253,1      14176    922119 /usr/lib/x86_64-linux-gnu/libb64.so.0d
transmiss 2327726 user  mem       REG              253,1      63400    930751 /usr/lib/x86_64-linux-gnu/libminiupnpc.so.17
transmiss 2327726 user  mem       REG              253,1      14176    929578 /usr/lib/x86_64-linux-gnu/libnatpmp.so.1
transmiss 2327726 user  mem       REG              253,1      75616    923850 /usr/lib/x86_64-linux-gnu/libpsl.so.5
transmiss 2327726 user  mem       REG              253,1     688160    920155 /usr/lib/x86_64-linux-gnu/libssl.so.3
transmiss 2327726 user  mem       REG              253,1     149384    918661 /usr/lib/x86_64-linux-gnu/libdeflate.so.0
transmiss 2327726 user  mem       REG              253,1     350608    925197 /usr/lib/x86_64-linux-gnu/libevent-2.1.so.7
transmiss 2327726 user  mem       REG              253,1     840632    918202 /usr/lib/x86_64-linux-gnu/libsystemd.so.0
transmiss 2327726 user  mem       REG              253,1     210968    919033 /usr/lib64/ld-linux-x86-64.so.2
transmiss 2327726 user    0r     FIFO               0,13        0t0  29236835 pipe
transmiss 2327726 user    1w     FIFO               0,13        0t0  29236836 pipe
transmiss 2327726 user    2w     FIFO               0,13        0t0  29236837 pipe
transmiss 2327726 user    4u  a_inode               0,14          0      1045 [eventpoll:7]
transmiss 2327726 user    5r     FIFO               0,13        0t0  29237600 pipe
transmiss 2327726 user    6w     FIFO               0,13        0t0  29237600 pipe
transmiss 2327726 user    7u  a_inode               0,14          0      1045 [signalfd]
transmiss 2327726 user    8u  a_inode               0,14          0      1045 [eventpoll:11,14,215,241,277,291,298,306,361,387,397,425,462,504,528,565,566,602,614,616,639,659,691,698,725,731,733,744,752,769,779,994...]
transmiss 2327726 user    9r     FIFO               0,13        0t0  29237601 pipe
transmiss 2327726 user   10w     FIFO               0,13        0t0  29237601 pipe
transmiss 2327726 user   11u  a_inode               0,14          0      1045 [eventfd:178]
transmiss 2327726 user   12u     unix 0x00000000a02a0df3        0t0  29237602 type=STREAM (CONNECTED)
transmiss 2327726 user   13u     unix 0x00000000783e2cfc        0t0  29237603 type=STREAM (CONNECTED)
transmiss 2327726 user   14u     IPv4           29238944        0t0       TCP *:8999 (LISTEN)
transmiss 2327726 user   15u     IPv6           29238945        0t0       UDP [MY IPV6 ADDR]:39738->[2001:1890:1112:1::20]:6969 
transmiss 2327726 user   16u     IPv6           29238946        0t0       TCP *:8999 (LISTEN)
transmiss 2327726 user   17u     IPv4           29238947        0t0       UDP 192.168.0.2:56512->192.168.0.1:5351 
transmiss 2327726 user   18u     IPv4           29238949        0t0       UDP *:8999 
transmiss 2327726 user   19u     sock                0,8        0t0  29301658 protocol: TCP
...
transmiss 2327726 user  613u     IPv6           29385906        0t0       TCP [MY IPV6 ADDR]:8999->[2408:823c:1010:1b8c:42b4:f50d:1d29:8363]:26198 (ESTABLISHED)
transmiss 2327726 user  614u     IPv4           29381821        0t0       TCP 192.168.0.2:8999->210.6.2.226:41785 (ESTABLISHED)
transmiss 2327726 user  615u     sock                0,8        0t0  29340188 protocol: TCP
transmiss 2327726 user  616u     IPv4           29384033        0t0       TCP 192.168.0.2:8999->113.89.150.56:11575 (ESTABLISHED)
transmiss 2327726 user  617u     sock                0,8        0t0  29284404 protocol: TCP
transmiss 2327726 user  618r      REG             253,10  496946670 193210789 /path/to/my/shared/file.1
transmiss 2327726 user  619u     sock                0,8        0t0  29283719 protocol: TCP
transmiss 2327726 user  620u     sock                0,8        0t0  29352928 protocol: TCP
transmiss 2327726 user  621r      REG             253,12  713473676  37748997 /path/to/my/shared/file.2
```
Other than ordinary files and TCP sockets, there are so many `transmiss 2327726 user  615u     sock                0,8        0t0  29340188 protocol: TCP` things. I guess that it is they which cause the 'too many open files' issue we are talking about.

**Comment by InsaneKnight** [comment]
With further observation, I have seen a socket
`transmiss 2346148 user  994u     IPv4           29519174        0t0       TCP 192.168.0.2:40834->172.64.172.7:81 (SYN_SENT)` 
became 
`transmiss 2346148 user  994u     sock                0,8        0t0  29519174 protocol: TCP` later. Since it did not become an ESTABLISHED connection, the reason of such transformation might be time-out. Is this issue caused by not cleanly closing time-out TCP sockets?

**Comment by ckerr** [comment]
Copying what @InsaneKnight wrote in 4616 here for visibility:

> Sadly this commit does not fix 3677, the leaked sockets seem to come from the http tracker client based on libcurl.

**Comment by ckerr** [comment]
This has been ameliorated by 4616 and reportedly the remaining issues are in curl, so I'm not sure what to do about them at this point.

I'm going to leave this ticket open but remove the 4.0.0 milestone; IMO this no longer blocks 4.0.0 stable

**Comment by ckerr** [comment]
Closing as a duplicate of #5385, which has more up-to-date info.
