### ISSUE TITLE
Torrent done script did not fired

### ISSUE THREAD

**Issue by SNBogdanov** [transmission/transmission#4885]
### What is the issue?

I have setup torrent done script on my windows daemon installation with v 3.0
I managed all access rights to script and download directories so everything works fine.
After installing v4 daemon several torrents fire done script and it worked correctly. But after that torrents remained in list (it should be removed by done script). 
After reinstalling v3 daemon everithyng goes back to normal.
Such behaviour was in early beta versions also.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0

**Comment by ckerr** [comment]
Hard to tell from this bug report but my first guess is that it's being caused by the bug fixed by https://github.com/transmission/transmission/pull/4879, since that could cause the torrent to not be marked as done even if it downloaded all the bytes.

I'd suggest trying a nightly build or building from `main` and seeing if that fixes the problem. Alternately, 4.0.1 will be out in a week.

If you try any of these approaches and the problem continues, please LMK

**Comment by ckerr** [comment]
Marking as `needs clarification` pending testing with a newer version

**Comment by SNBogdanov** [comment]
Unfortunately I can not build from nightly builds. I will try 4.0.1 as soon as it will be available. A nd I will post the result here

**Comment by celestinoxp** [comment]
> Unfortunately I can not build from nightly builds. I will try 4.0.1 as soon as it will be available. A nd I will post the result here

Maybe help: https://build.transmissionbt.com/

**Comment by SNBogdanov** [comment]
I installed nightly build transmission-4.0.0-dev+r9d1a141482-x64.msi and situation is not fixed.

**Comment by SNBogdanov** [comment]
Tried to get torrent info via torrent-remote in json format. 
{"arguments":{"torrents":[{"error":0,"errorString":"","eta":-1,"id":3,**"isFinished":false**,"leftUntilDone":0,"name":"London.River.","peersGettingFromUs":0,"peersSendingToUs":0,"rateDownload":0,"rateUpload":0,"sizeWhenDone":1010153158,"status":6,"uploadRatio":0}]},"result":"success","tag":6}

**Comment by SNBogdanov** [comment]
4.0.1 did not fix the problem

**Comment by SNBogdanov** [comment]
4.0.1 did not fix the problem

**Comment by SNBogdanov** [comment]
4.0.1 did not fix the problem

**Comment by ckerr** [comment]
@SNBogdanov OK so to clarify, the torrent-done script is not being called when a torrent completes?

**Comment by ckerr** [comment]
> Torrent done script did not fired #4885

&nbsp;
> After installing v4 daemon several torrents fire done script and it worked correctly. But after that torrents remained in list (it should be removed by done script).

So the issue is that the script isn't called?

Or that the script is called but doesn't remove the torrents?

I'm unsure what problem is being reported here.

**Comment by SNBogdanov** [comment]
Problem is that script is not called at all. In json output torrent is not marked as completed. Even if it is 100% dowloaded. It started to seed it and status shows Seeding.

> > Torrent done script did not fired #4885
> 
>  
> 
> > After installing v4 daemon several torrents fire done script and it worked correctly. But after that torrents remained in list (it should be removed by done script).
> 
> So the issue is that the script isn't called?
> 
> Or that the script is called but doesn't remove the torrents?
> 
> I'm unsure what problem is being reported here.
Problem is that script is not called at all. In json output torrent is not marked as completed. Even if it is 100% dowloaded. It started to seed it and status shows Seeding.

**Comment by ckerr** [comment]
> json output torrent is not marked as completed. Even if it is 100% downloaded. It started to seed it and status shows Seeding.

While it's seeding, what status does the json output say the torrent has?

**Comment by SNBogdanov** [comment]
status 6

**Comment by SNBogdanov** [comment]
{"arguments":{"torrents":[{"error":0,"errorString":"","eta":-1,"id":3,"isFinished":false,"leftUntilDone":0,"name":"London.River","peersGettingFromUs":0,"peersSendingToUs":0,"rateDownload":0,"rateUpload":0,"sizeWhenDone":1010153158,"status":6,"uploadRatio":0}]},"result":"success","tag":6}

**Comment by ckerr** [comment]
@SNBogdanov OK so to clarify, the torrent-done script is not being called when a torrent finishes _downloading_? Or finishes _seeding_?

It looks like this is a seeding torrent, so I wouldn't expect the seeding-done script to be called yet

**Comment by SNBogdanov** [comment]
I have torrent done script. The same config works correctly on v.3

**Comment by ckerr** [comment]
@rasa2k is this a script to be called when the torrent is done downloading, or one to call when it's done seeding?

**Comment by rasa2k** [comment]
@ckerr it's a script to be called when the torrent is done downloading.

**Comment by mtaliaf** [comment]
I am having the same issue as described above on linux.

```
    "script-torrent-added-enabled": false,
    "script-torrent-added-filename": "",
    "script-torrent-done-enabled": true,
    "script-torrent-done-filename": "/home/mtaliaf/.local/bin/torrent_done",
    "script-torrent-done-seeding-enabled": false,
    "script-torrent-done-seeding-filename": "",
```
  
I can confirm that the done script is not being called at all because i have tested it with the first line just echoing out to /tmp and no file is created.

**Comment by mikedld** [comment]
I take it you checked the log and there were no "Calling script '{path}'" (info) and "Couldn't call script '{path}': {error} ({error_code})" (warning) messages in it?

**Comment by hansyulian** [comment]
Hi, i'm reporting same behaviour in the version 4.0.3. I was also using v3 and the same script is working fine.

**Comment by mikedld** [comment]
> @ckerr it's a script to be called when the torrent is done downloading. "script-torrent-done-filename": "C:\Users\Administrator\Desktop\transmissionCompleted.cmd", "script-torrent-done-seeding-enabled": false,

@rasa2k, If you're editing the configuration file by hand, note that in JSON backslashes are used for escaping, and so need to be escaped themselves, i.e.

```json
  "script-torrent-done-filename": "C:\\Users\\Administrator\\Desktop\\transmissionCompleted.cmd",
```

Alternatively, you could use forward slash as path separator on Windows:

```json
  "script-torrent-done-filename": "C:/Users/Administrator/Desktop/transmissionCompleted.cmd",
```

**Comment by pancho-villa** [comment]
I moved the script to the same folder as my downloads to fix my script.

Here's some more context about how I resolved this issue. I upgraded my Ubuntu 23.04 server to 23.10, and transmission kept throwing read-only filesystem errors. I [found this stackexhange post](https://unix.stackexchange.com/questions/731364/transmission-cant-access-mount-read-only-file-system) that said to update the systemd unit file adding the bindpaths directive. This fixed the read-only error. When troubleshooting why my post download script wasn't working, I thought it might be related to this. I moved the script from a different location into the transmission download location and it started working again.

I suspect it was some fundamental change to systemd permissions that was the ultimate cause in my case.
