### ISSUE TITLE
Cannot Resolve No Data Found for Individual File

### ISSUE THREAD

**Issue by abramjstamper** [transmission/transmission#5240]
### What is the issue?

I have an older torrent from an old file that was incompletely downloaded on the version of Transmission prior to v4.0.2. The torrent is of an individual file, instead of a folder. Upon upgrading and starting up Transmission v4.0.2 from v3.x, most things moved over okay, but a few files came back as `No data found! Ensure your drives are connected or use "Move Data File To…". To re-download, remove the torrent and re-add it.`. 

I know the file is still available on a local network storage solution, I go to `Move Data File To…` option on the torrent. It opens a file dialog. I navigate to the NAS, then the correct folder, but all the individual files are grayed out in the file dialog. I can see the file in the dialog, but can't select it. The file name is `<file>.<file_ext>.part`. The `Move Data File Too…` function works fine for folders. It seems like it's only broken for individual files. Even if I remove, the `.part` from the end of the file name, it still does not allow me to select it in the file browser within Transmission when trying to `Move Data File Too…`.

Apologies if this has already been reported, but I did check open/closed issues and was unable to find it.

### Which application of Transmission?

macOS app using Mac OS 10.14.6

### Which version of Transmission?

4.0.2

**Comment by NHOrus** [comment]
Having same error.

**Comment by YurikaL** [comment]
I believe that I've got a clue of some sort for this issue. For some reason, in such single-file torrents Transmission 4.x substitutes the name of an individual file (but not the torrent name itself) with the `magnet-info:display-name` field, which look identical to `dn` field from the original magnet link. This `dn` field may be differ from the actual torrent name, and in fact is often different. So it seems that this issue affects all single-file torrents downloaded from a magnet link, where the `dn` field differs from the actual torrent name.

BTW, cannot find any info for `magnet-info` field, is it a unique way for Transmission to store data from the original magnet?

**Comment by ckerr** [comment]
@YurikaL what you're describing sounds like #5378, fixed in 4.0.3.

Does 4.0.3 fix the problem?

**Comment by abramjstamper** [comment]
It seems it's not fixed in 4.0.3. I still have several torrents that say the data file has been moved. When I try to use the `Move Data File To...` option to relink the torrent in Transmission with the partially downloaded file, all the files are grayed out. Maybe a latent issue even with #5378?#5331 

As @genericusername3 points out, if you first save a torrent file to the desktop, then remove the torrent from Transmission's queue. It's possible to re-add the torrent from the file. I navigated to the correct location and it automatically verified the pieces already downloaded. Seems like the work around does fix it, but will have to be done for every partially downloaded torrent.

**Comment by YurikaL** [comment]
There are mixed results with 4.0.3: seems like the file names of all newly added magnet links are now correct (and output of `transmission-show`, which was affected too, is also correct), but file names in (almost) all existing affected torrents are still incorrect, so there are still errors. (Oddly enough, but only ONE torrent from my client with individual file and different `display-name` somehow kept the correct file name.)
So maybe that magnet names are already saved by 4.0.2 in the resume data as custom renamed file names? If you rename that single file back, then recheck and force start torrent, error will be gone without deleting and re-adding.

BTW, I made [this script](https://gist.github.com/YurikaL/a14dd67769fc42c478a7faaf537d65b6) to find all probably affected torrents. Dependencies: [transmission-rpc](https://github.com/trim21/transmission-rpc/) and [fastbencode](https://github.com/breezy-team/fastbencode). It might be a bit of messy, because I'm not experienced in programming at all, but it works for me! Maybe I just should turn it into a migration script that will rename files in all affected torrents. Any advice is appreciated!

**Comment by tearfur** [comment]
Closing. Voice out if this is still an issue in newly added torrents in `4.0.3`.

**Comment by tearfur** [comment]
Closing. Voice out if this is still an issue in newly added torrents in `4.0.3`.
