### ISSUE TITLE
Re-ordering torrents gives unexpected results & order changes upon re-opening

### ISSUE THREAD

**Issue by frozenpandaman** [transmission/transmission#5321]
### What is the issue?

Running Transmission 4.0.2 (2a57b17031) on macOS 12.6.3 (M1/ARM architecture).

This is while View > Sort Transfers By is set to "Queue Order" (which allows manual reordering).

Here are some torrents (public domain books from the Internet Archive) I've loaded into Transmission:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/7245874/228432531-ac41e3d0-1b7b-4640-8363-3b43879fa748.png">

Upon closing Transmission and reopening, this is what the UI shows:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/7245874/228432647-a9017c72-506b-4ca5-a6d3-67df54b190d4.png">

If I try changing the order of these torrents, unexpected results occur: (gif below)
<img width="640" alt="image" src="https://user-images.githubusercontent.com/7245874/228434021-d7c91de3-cbc0-448d-b45a-9041fb3bcae4.gif">

This happens to torrents no matter if they're in a group or not.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.2

**Comment by killemov** [comment]
Yes, the drag & drop reordering looks weird and not to be working. But what are you reordering in that way anyway? (queuePosition perhaps?)

**Comment by killemov** [comment]
@frozenpandaman Do you know on WHAT property you are reordering? Because there is no "visual ordering" in the RPC-spec.

**Comment by frozenpandaman** [comment]
What? From what I can tell, the RPC spec is about "interacting with Transmission sessions remotely". That's not what I'm doing here. This is just the application on my computer.

I don't see how this conversation is helping, or how it's relevant. I'm going to wait for a reply from one of the maintainers as to not further spam up this thread.

**Comment by killemov** [comment]
So you actually believe Transmission (ANY client) keeps track of the visual ordering?  I could be wrong but my bet is that a component was used that allows you to reorder, but that functionality was not turned off.

**Comment by GaryElshaw** [comment]
This is a known regression in the macOS client #327.

**Comment by frozenpandaman** [comment]
Thanks for linking the isssue @GaryElshaw! Hopefully this will get fixed in the near future. Not sure if that is only about preserving the order in between sessions, as the title implies, or if it also accounts for the [wonky behavior](https://user-images.githubusercontent.com/7245874/228434021-d7c91de3-cbc0-448d-b45a-9041fb3bcae4.gif) when trying to re-order _any_ torrents sometimes which I also included in my post.

**Comment by GaryElshaw** [comment]
The wonky behaviour will probably need some more testing. Probably a silly question, but i know i have more than once gone to 'View' -> 'Sort transfers by' and discovered that the sort order i had stipulated was 'Queue Order' and not 'Activity' or vice versa that i'd forgotten about.

**Comment by frozenpandaman** [comment]
Good tip, I actually had not used that menu. The only one of those options that allows you to drag-and-drop reorder torrents is "Queue Order" (set to anything else, you can only drag torrents between groups to change which they're in) – so it's definitely been set to "Queue Order" this whole time, including between sessions and in all my images/gifs in the OP.

**Comment by GaryElshaw** [comment]
Thanks @frozenpandaman, that's realy good information for whomever tackles the regression to know that Queue Order is set and this occurs.

**Comment by fsafq41** [comment]
same problem. Started from 4.0 and still present in 4.0.2. Same issue on 2 separate Macs (1 Apple Silicon on latest Ventura, and 1 Intel on latest Monterey).

Very strange: re-opening Transmission, the order of the list is completely different, and when drag-doping items they jumped in random locations in the list

**Comment by GaryElshaw** [comment]
> Has this been fixed in 4.0.3?

No, not yet #155

**Comment by ckerr** [comment]
I think this is a duplicate of #155, that queue order is not being saved between sessions so that when you reopen a session the ordering is all changed.

Is that correct?

**Comment by allanjackson** [comment]
> I think this is a duplicate of #155

Oh man, other people have been dealing with this bug since 2017? That doesn't leave me hopeful for a quick fix...

**Comment by GaryElshaw** [comment]
Yep.

**Comment by frozenpandaman** [comment]
@ckerr @GaryElshaw Yes, but from my understanding it's not only that – as shown, changing the sort order during the same session as well can cause everything to be re-ordered. But perhaps it's all stemming from the same underlying issue. That said, I'm not completely sure if it's the same as the bug from 2017 (!) or not but hoping that'll be addressed now that it's affecting all Mac users as well as everyone else... a pretty huge issue!

**Comment by GaryElshaw** [comment]
For macOS, the manually sorted feature between sessions, i think, somehow got misplaced, lost, or somehow over-written throughout the 4.0 development process. The other thing to keep in mind is that the sort order during a session is also controlled by the user preference in View --> Sort Transfers By. Often users can overlook that setting during upgrades because once set to whatever your preference might have been, it's easy to forget that you even did it.

**Comment by frozenpandaman** [comment]
@GaryElshaw Yep, that would make sense to me. In my OP I mentioned that "This is while View > Sort Transfers By is set to "Queue Order" (which allows manual reordering)" – since none of the other options allow you to drag torrents around like this. And personally, I don't ever use any of the others. Appreciate you providing additional context and will look forward to this hopefully being addressed (at least on Mac) & am happy to help with testing out potential fixes or whatever's needed!
