### ISSUE TITLE
torrents stuck at 99.99% introduced in 4.1.0-beta.3

### ISSUE THREAD

**Issue by calculon0** [transmission/transmission#7919]
### What is the issue?

This is a follow up of #7834. The issue still occurs on 4.1.0-beta.4 and main branch as of a8e20bf358f362e734328a894ed76e9481d73e8e.

Some torrents will hang or get stuck at 99.99% with download speed of 0 bytes/s. 

- Manually verifying local data will either 1) verify the data and the torrent completes, or 2) verify the data, download more data, and the torrent completes.
- Pausing and restarting the torrent will usually complete the torrent.

Logs are from transmission-daemon from #7903.
[transmission2.log.gz](https://github.com/user-attachments/files/24083842/transmission2.log.gz)

I can reproduce this on macOS app as well.

### Which application of Transmission?

macOS app

### Which version of Transmission?

a8e20bf358f362e734328a894ed76e9481d73e8e

**Comment by tearfur** [comment]
New test build ready at #7903.

**Comment by calculon0** [comment]
Here are the logs.

[transmission.log.gz](https://github.com/user-attachments/files/24131728/transmission.log.gz)

Also, I'm getting an error when I try to `./transmission-remote --list`

```
~/Downloads/transmission/bin$ ./transmission-remote --list
Error: no method name
```

It's not a problem, since I can use the GUI, but `--list` worked previously.

**Comment by tearfur** [comment]
I think I've caught a tail of what's happening. The gist of it is that these are the conditions where the bug happens:

1. The torrent's block boundaries and piece boundaries does not align (they do in most torrents).
2. The missing block is always on the boundary of 2 pieces with whose boundary is not aligned with the block's boundaries.

I will write up a fix these few days and see how it goes.

**Comment by tearfur** [comment]
@calculon0 Can you test #7944 to see if it fixes the problem? If it doesn't, then I will update the debug logs again for another test build.

**Comment by calculon0** [comment]
@tearfur This fixes the problem for me in transmission-daemon on linux. Thanks!

I'm not sure if it's also supposed to fix it on macOS, but I can reproduce it on the #7944 macOS app, and it also sometimes crashes.

**Comment by tearfur** [comment]
> I'm not sure if it's also supposed to fix it on macOS

The fix is supposed to apply to all Transmission clients, so yes.

> but I can reproduce it on the [#7944](https://github.com/transmission/transmission/pull/7944) macOS app

Ah, bummer.

> and it also sometimes crashes

I can't be sure without seeing some stack traces, but you are most likely seeing an unrelated issue that is being worked on at #7948.

**Comment by tearfur** [comment]
New test build ready. #7903

**Comment by calculon0** [comment]
I haven't been able to reproduce this with transmission-daemon on linux. But I'm now seeing a different issue which may or may not be related. The download gets stuck at 99.9% but the torrent continues to download. Here are 2 logs of this happening. The first one the download speed continued at 10MB/s for about 10 min and never completed. The second one the download speed was 1MB/s and never completed.

Log 1: (I had to add *.log to the filename to upload them, but they are tar xz files that have been split)
[transmission_downloading.tar.xz.aa.log](https://github.com/user-attachments/files/24243797/transmission_downloading.tar.xz.aa.log)
[transmission_downloading.tar.xz.ab.log](https://github.com/user-attachments/files/24243798/transmission_downloading.tar.xz.ab.log)

Log 2:
[transmission_downloading2.tar.xz.log](https://github.com/user-attachments/files/24243850/transmission_downloading2.tar.xz.log)

I can still reproduce this on the mac app (although much less frequently). I tried to capture the log from the macos app, but the log window doesn't let me save the whole file, just the last X lines.

[macos_app_stuck.log](https://github.com/user-attachments/files/24243886/macos_app_stuck.log)

**Comment by tearfur** [comment]
I'm busy with other topics within the project at the moment. I will come back to look at the remaining issues on mac.

**Comment by tearfur** [comment]
New test build ready #7903.

I expect this build to no longer keep downloading to nothingness at 99.9%, but the cause of being stuck at 99.9% is not yet understood, so I still expect that to happen.

**Comment by tearfur** [comment]
I just pushed another fix to #7903. It fixes yet another edge case, but the cause of being stuck at 99.9% remains unsolved.

If you can reproduce the problem, please attach logs again.

**Comment by uralets** [comment]
No idea whether it's the same issue. It has stayed at 99.9% for quite some time, but has completed after a pause/unpause (but not immediately):

<img width="1440" height="1046" alt="Image" src="https://github.com/user-attachments/assets/684b72fa-686a-4688-b917-9ea91d71d3f2" />

**Comment by calculon0** [comment]
@uralets that sounds like the same issue I've been experiencing.

I tested macOS app 4.1.0-beta.5 and it happens much less frequently, but I was able to reproduce it (after ~50 successful downloads, it triggered once). I tried to save logs from https://github.com/transmission/transmission/pull/7903 on linux, but I am not able to log anything from transmission-daemon.

- downloaded ubuntu-22-04-from-tarball artifact from #7903 
- run ./transmission-daemon &> test.log
- there is no output to the test.log file

I'll try to build from source and see if I can save the logs when it happens.

@tearfur I know you deleted the branch, but I can manually apply the code changes. Is the code in https://github.com/transmission/transmission/pull/7903 still helpful to debug this?

**Comment by tearfur** [comment]
I've restored and updated #7903.

Not sure why you're not getting logs from the ubuntu artifact (assuming you did specify  `--log-level=info` when starting the daemon`). But anyway, now that #7903 is restored, hopefully things should work again.

**Comment by calculon0** [comment]
I tried #7903 again, but I still cannot get any output. I tried ubuntu-22-04-from-tarball and debian-11-from-tarball with the command `./transmission-daemon --log-level=info &> test.log` but there is nothing output to the file.

Can someone else test the artifacts and confirm the daemon is outputting something to the log file?

**Comment by tearfur** [comment]
I think you are missing the `-f` option, which tells the daemon to run in the foreground instead of forking to a background process.

P.S. I'm curious how did you produce that last few logs if you didn't know that. 😅

**Comment by calculon0** [comment]
That fixed the output problem, thanks. I'm really not sure how I produced the other logs, haha. It's very possible I used `-f` before, and then forgot about it after the holidays.

It took many tries to reproduce the problem, but I was able to reproduce the problem on the mac version of transmission-daemon from #7903.

This log file has multiple torrents, but the problem torrent is PROBLEMFILE.mkv. The extracted log file is about 4GB. It stays stuck at 99.9% for 30 min and continues to download at 20KB/s but never completes.

[logfile.tar.zst.part-aa.log](https://github.com/user-attachments/files/24688720/logfile.tar.zst.part-aa.log)
[logfile.tar.zst.part-ab.log](https://github.com/user-attachments/files/24688719/logfile.tar.zst.part-ab.log)

**Comment by tearfur** [comment]
Hmm, this time the wishlist doesn't seem to be the problem. I guess this is good news for the wishlist, but it suggests a potential problem elsewhere.

### To summarise my observation

Your download was stuck on 3 blocks. Notably, all 3 of them are sitting on a piece boundary.

- Block 12087: Spans across pieces 425 and 426.
- Block 19578: Spans across pieces 689 and 690.
- Block 25253: Spans across pieces 889 and 890.

And even more notably, these 3 cases exhibited a similar pattern:

1. The former piece completed first (pieces 425, 689, 889).
2. The latter piece then failed the checksum test (pieces 426, 690, 890), and thus the block needs to be re-downloaded.
3. The same Tixati client keeps rejecting Transmission's request to download this block, and Transmission stubbornly keeps re-sending the request to the Tixati client.

### The problems

- Tixati keeps rejecting these blocks for some reason.

   If I had to guess the reason, the Tixati client might be thinking that Transmission is re-downloading the block for no good reason, since Transmission told Tixati that it has a piece that contains the block, and so they rejected the requests. E.g. Transmission finished piece 425 => Transmission sends a `HAVE` message to Tixati => Tixati rejects any future requests for blocks inside piece 425, including block 12087 that was later invalidated by piece 426's failed checksum test.
- Transmission does not try another client for 30 minutes.

**Comment by tearfur** [comment]
@calculon0 #8233 should fix Transmission not trying another peer for a long time, please try it out when you've got the time.

OTOH, I still need to investigate further to find out what happened between your Transmission client and the Tixati client that refused to send the 3 stalled blocks.

**Comment by Lukaszpl666** [comment]
Happend to me today with the newest Transmission for MacOS
4.1.0 (272401184f)

Did a "varify local data" and slowly but smth started to download

<img width="385" height="379" alt="Image" src="https://github.com/user-attachments/assets/3c08d369-7607-4cff-99a5-603acf891691" />

**Comment by tearfur** [comment]
@Akczht This issue is only about 99.99% when *downloading*. You're probably experiencing a different issue.

For example, because qBittorrent and Transmission sanitises invalid filenames differently, Transmission might be unable to find files downloaded by qBittorrent that has an invalid filename.

**Comment by Verkhovskyi** [comment]
Experiencing this issue on stable 4.1.0 in Docker container on Unraid 7.2.3

**Comment by stevenshea** [comment]
Experiencing this issue on stable 4.1.0 in Docker container on Debian 13.3

**Comment by calculon0** [comment]
I haven't been able to reproduce it on #8233. Thanks for the work @tearfur.

To be clear, sometimes torrents will get to 99.99% and it will take somewhere between 2-10 min to complete. But that seems to be a slow completion problem rather than being completely stalled.

**Comment by ckerr** [comment]
Marking this as fixed based on @calculon0's feedback. If anyone still sees this in 4.,1.1 please open a new ticket. Thanks!

**Comment by calculon0** [comment]
I spoke too soon. It happened again on #8233. @tearfur can you create another test build with logging? I can try to get you logs of it happening.

**Comment by tearfur** [comment]
New test build ready at #7903.

**Comment by calculon0** [comment]
Here is the log.

[logfile.tar.zst.log](https://github.com/user-attachments/files/25242141/logfile.tar.zst.log)

**Comment by emwgee** [comment]
Still happens on Transmission from Synocommunity (ver 4.1.0-28) on Synology NAS, with transmission QT on Windows 11 as remote client.

Many times torrents reached around 99%, and the download will continue for a very long time, sometime over an hour before completion.

A manually verification of local data will kick start the download again, the download normally completes in a few seconds after the verfication, but sometimes it take several manually verifications in order to work.

If  the torrent at 99% is left alone without manual verfication of local data, it will take a much longer time before the download is completed.

<img width="450" height="404" alt="Image" src="https://github.com/user-attachments/assets/be075f1a-7e53-4ebf-a326-dabb52354844" />

**Comment by h1de0x** [comment]
@tearfur 

I have reproduced a "stalled download" issue on the per-peer-per-block-2 branch. While the Web UI remains responsive, the torrent download progress stops completely (0 KB/s) for several minutes before finally completing.

Steps to Reproduce:

1. Start a download (e.g., small file ~84MB).
2. Pause and manually corrupt several pieces using dd to simulate hash failures:  `for i in 10 100 250 450; do dd if=/dev/urandom of="file.pdf" bs=131K count=1 seek=$i conv=notrunc; done`
3. Perform "Verify Local Data".
4. Start the torrent.

It seems Wishlist::Impl::next() doesn't know when to stop. It repeatedly picks pieces that are not yet finished but have zero unrequested blocks (all blocks are already in-flight).

Candidate::compare(). It currently prioritizes pieces with the smallest unrequested.size(). This effectively pushes pieces with unrequested.size() == 0 to the very top of the queue, making the scheduler spin on them indefinitely.

[test1.log.tar.gz](https://github.com/user-attachments/files/25640010/test1.log.tar.gz)

**Comment by tearfur** [comment]
@amatus- I don't see anything wrong from your logs except for the fact that the last few block requests `[3688, 3695]` timed out 2 times each (all qBittorrent peers) before finally completing. The wishlist was working as designed for you as far as I'm concerned.

Maybe Transmission's behaviour is somehow causing libtorrent-rasterbar to throttle us, but I don't really know the reason. If you know why that is, I'm very interested to hear it.

> It seems Wishlist::Impl::next() doesn't know when to stop. It repeatedly picks pieces that are not yet finished but have zero unrequested blocks (all blocks are already in-flight).

That's not what's happening. `Wishlist::Impl::next()` merely checked for unrequested blocks in incomplete pieces. And because there is none, no new requests were sent out.

> Candidate::compare(). It currently prioritizes pieces with the smallest unrequested.size(). This effectively pushes pieces with unrequested.size() == 0 to the very top of the queue, making the scheduler spin on them indefinitely.

That's just because all incomplete blocks are already requested, so it appears to "spin indefinitely".

**Comment by tearfur** [comment]
@calculon0 I found another bug from your logs, fix is up at #8644 now.

**Comment by h1de0x** [comment]
@tearfur I understand that the logic is functionally correct. However, I'm concerned about the event density. If next() is being called so frequently that it floods the debug log with thousands of lines per second, doesn't this polling create an unnecessary CPU overhead? Wouldn't it be more efficient to have a backoff or an event-driven trigger when no unrequested blocks are available?

**Comment by tearfur** [comment]
@amatus- Please create a new issue for your topic, we'll continue there.

**Comment by calculon0** [comment]
@tearfur I'm using #8644 and I have a torrent that is consistently stopping around 98-99% with download speed at 0kb and uploads continuing. This is different than before which would always stop at 99.9%. Could you add debug logging to #8644? I can try to capture it happening.

**Comment by calculon0** [comment]
@tearfur nevermind, I merged your logging code into #8644 and ran it to generate logs.

[test.log.tar.zst.log](https://github.com/user-attachments/files/25733409/test.log.tar.zst.log)

**Comment by tearfur** [comment]
@calculon0 I just pushed to #8644. Please try again.

**Comment by calculon0** [comment]
@tearfur thanks, that seems to have fixed the issue. Using #8644, I haven't run into the bug so far.

**Comment by tearfur** [comment]
@calculon0 I've closed #7903 again.

Thanks for following up on this issue for such a long time. Your logs have been a treasure trove of edge cases, and I can't emphasise enough how useful they were.

**Comment by calculon0** [comment]
@tearfur No problem, happy to help. Thanks for all your hard work tracking down the bugs and fixing them.
